Repository openqda/openqda, pull requests merged in 2024-06, with the labels that each got.

#37 Feature/add tests with pest
  .github/workflows/backend_lint.yml
  .github/workflows/backend_tests.yml
  docs/BACKEND-TESTING.md
  web/app/Actions/Fortify/CreateNewUser.php
  web/app/Actions/Jetstream/DeleteTeam.php
  web/app/Providers/AuthServiceProvider.php
  web/composer.json
  web/composer.lock
  web/database/factories/ProjectFactory.php
  web/database/factories/TeamFactory.php
  web/phpunit.xml
  web/tests/ArchTest.php
  web/tests/Feature/CreateTeamTest.php
  web/tests/Feature/DeleteAccountTest.php
  web/tests/Feature/DeleteTeamTest.php
  web/tests/Feature/RegistrationTest.php
  web/tests/Feature/RemoveTeamMemberTest.php
  web/tests/Feature/UpdateTeamMemberRoleTest.php
  web/tests/Pest.php
Labels: documentation, CI

#35 Feature: Add Import/Export Functionality for Codebooks with Basic UI
  web/app/Http/Controllers/CodebookCodesController.php
  web/app/Http/Controllers/CodebookController.php
  web/app/Http/Controllers/ProjectController.php
  web/app/Http/Controllers/SourceController.php
  web/app/Models/User.php
  web/composer.json
  web/resources/js/Components/project/Codebook.vue
  web/resources/js/Components/project/NewCodebookForm.vue
  web/resources/js/Pages/CodingPage.vue
  web/resources/js/Pages/ProjectOverview.vue
  web/routes/web.php
Labels: enhancement, live (staging)

#36 Add missing community docs
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation

#40 Feature: Transcription via aTrain integration
  docs/DEBUG-WEBSOCKETS.md
  services/transform/README.md
  services/transform/atrain/.gitignore
  services/transform/atrain/Dockerfile
  services/transform/atrain/Pipfile
  services/transform/atrain/Pipfile.lock
  services/transform/atrain/README.md
  services/transform/atrain/app/__init__.py
  services/transform/atrain/app/audio.py
  services/transform/atrain/app/install.py
  services/transform/atrain/app/loader.py
  services/transform/atrain/app/main.py
  services/transform/atrain/app/prestart.sh
  services/transform/atrain/app/process.py
  services/transform/atrain/requirements.txt
  services/transform/convert-rtf-to-html/convert_rtf_to_html.py
  services/transform/convert-rtf-to-html/convert_rtf_to_html_locally.py
  services/transform/convert-rtf-to-html/readme.md
  web/.dockerignore
  web/.env.example
  web/app/Actions/Jetstream/DeleteTeam.php
  web/app/Events/ConversionFailed.php
  web/app/Http/Controllers/SourceController.php
  web/app/Jobs/ConvertFileToHtmlJob.php
  web/app/Jobs/TranscriptionJob.php
  web/app/Listeners/DeleteSourceFiles.php
  web/app/Models/Source.php
  web/app/Services/SourceService.php
  web/config/app.php
  web/config/convertrtftohtml.php
  web/config/internalPlugins.php
  web/docker-compose.yml
  web/docker/8.3/Dockerfile
  web/docker/8.3/php.ini
  web/docker/8.3/start-container
  web/docker/8.3/start_debug_services.sh
  web/docker/8.3/supervisord.conf
  web/eslint.config.js
  web/package-lock.json
  web/package.json
  web/resources/js/Components/files/FilesImporter.vue
  web/resources/js/Components/files/FilesList.vue
  web/resources/js/echo.js
  web/routes/web.php
  web/start_debug_services.sh
Labels: enhancement, live (staging)

#50 Bugfix: utf-8 compatibility for txt files
  .github/workflows/backend_lint.yml
  web/app/Http/Controllers/SourceController.php
Labels: bug

#52 docs: Create Backend refactoring guidelines
  docs/BACKEND-REFACTOR-GUIDELINES.md
Labels: documentation, code quality

#53 Bugfix: send navigation updates only when in a team
  web/resources/js/Layouts/AppLayout.vue
Labels: bug
